### ISSUE TITLE
Widget Spacing on edges of screen is off

### ISSUE THREAD

**Issue by hnlkaitan** [PoomSmart/Anywhere-Widgets-for-iPad#1]
**Device**: iPad Pro 11" (2018)
**iPadOS Version**: 14.3
**Tweak List**: [Pastebin](https://pastebin.com/yyW4L5Ac) 

I noticed that widgets that are in either the right-most (or left-most) columns are spaced further out the the rest of the icons in that column. 
![5477D157-CB61-4F0A-AEE8-91DE8475CD6A](https://user-images.githubusercontent.com/29077299/114288853-a3f3d480-9a27-11eb-9a1e-d5198dd2ff6a.jpeg)

I've also tried disabling FolderControllerXIII and PrimalFolder 2, and the widget offset is still there. If there's any more information I can provide let me know!

**Comment by PoomSmart** [comment]
Fixed in version 1.3
