### ISSUE TITLE
Anywhere widgets for iPad

### ISSUE THREAD

**Issue by megatech1966** [PoomSmart/Anywhere-Widgets-for-iPad#2]
Anywhere widgets for iPad is not working on a iPad Pro 12.9 2nd generation. All you see is 4 icons on each corner and you can't put a widget on your homescreen.

**Comment by PoomSmart** [comment]
More information required. iOS version? Screenshot? List of installed tweaks?

**Comment by megatech1966** [comment]
iOS 14.3

**Comment by megatech1966** [comment]
It does work. You have to select normal size icons. Not big icons.
