### ISSUE TITLE
Can't add widgets on iPad Pro 9.7

### ISSUE THREAD

**Issue by theIuser** [PoomSmart/Anywhere-Widgets-for-iPad#3]
Hi,
I got an iPad Pro 9.7 on iOS 14.1 and I'm facing the following issue:
When I turn my iPad in landscape I only see four apps on my homescreen one app in each corner.
I also can't add widgets at all. I don't see the + in wiggle mode.

Please let me know if you need any further informations.
Thanks for your help

**Comment by PoomSmart** [comment]
List all your installed tweaks.

**Comment by theIuser** [comment]
Cercube for Youtube
DeleteForever
EmojiKey
Filza File Manager
iSponsorBlock
LetMeBlock
NoClipboardforYou
NoLargeTitles
RealCC
Rocket for Instagram
SugarCane
TwitterNA

Is that enough or do you need all the libaries too? (Alderis Color Picker, APT, APT (apt-key)...)
Thanks

**Comment by PoomSmart** [comment]
It's fine. Can you also include some screenshots that you say you only see 2 by 2 apps per page?

**Comment by theIuser** [comment]
Here you go.
![IMG_3922](https://user-images.githubusercontent.com/23708374/120012762-394f2600-bfe0-11eb-9e38-38b73f6d2862.jpg)
![IMG_3924](https://user-images.githubusercontent.com/23708374/120012770-3a805300-bfe0-11eb-932a-f015a4a436ce.jpg)
As you can see no + in wiggle mode
![IMG_3923](https://user-images.githubusercontent.com/23708374/120012772-3bb18000-bfe0-11eb-9c28-71b3ff071201.jpg)

**Comment by PoomSmart** [comment]
Are there any SpringBoard related or home screen customization tweaks on your iPad?

**Comment by theIuser** [comment]
No, the only one I can think of is NoLargeTitles. But I removed this one for testing but it didn't make any difference.

**Comment by PoomSmart** [comment]
Will the problem go away if you uninstall my tweak and IconState tweak?

**Comment by theIuser** [comment]
Yes anything goes back to a normal state as soon as I uninstall your tweak and IconState

**Comment by PoomSmart** [comment]
What jailbreak do you use?

**Comment by theIuser** [comment]
I use checkra1n on this iPad

**Comment by HackZy01** [comment]
I thought it is supposed not to show the +, it only shows in today view and you drag it from there

**Comment by theIuser** [comment]
Found the workaround.
In settings under Home Screen and Dock you need to enable "More" and not "Bigger". Afterwards I was able to add widgets to my homescreen.
