### ISSUE TITLE
Cannot open app folder in the widget view on the side

### ISSUE THREAD

**Issue by ghost** [PoomSmart/Anywhere-Widgets-for-iPad#4]
I had installed this tweak about 3 days ago, i tried to add a folders in the widget view, i tapped to turn off the wiggle mode and then when i tap on the folder it just dimms itself and then the springboard crashes. It would be very helpful if you fix this in the next update

Thank You !

**Comment by PoomSmart** [comment]
Crash log needed. A video recording for what you did will also be helpful.
